version: '3.9'
services:
  app:
    build:
      context: ./infra/app
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    build:
      context: ./infra/db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    name: book_memory_db
